services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: backend_development
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
  backend:
    networks:
      default:
        aliases:
          - backend.local
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: rails-container
    volumes:
      - ./backend:/app
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-container
    volumes:
      - ./frontend:/app
    command: "npm run dev -- -p 3001"
    ports:
      - "3001:3001"
    tty: true
    stdin_open: true

volumes:
  mysql-db: