FROM ruby:3.4.1

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install -y build-essential nodejs default-mysql-client vim

COPY Gemfile Gemfile.lock /app/

RUN gem install bundler
RUN bundle install

COPY . /app

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

CMD ["bundle", "exec", "sidekiq"]